(() => {
  const wizard=document.getElementById("matchWizard"); if(!wizard)return;
  const form=document.getElementById("travelMatchForm"),steps=[...form.querySelectorAll(".match-step")],next=document.getElementById("matchNext"),back=document.getElementById("matchBack"),bar=document.getElementById("matchProgressBar"),label=document.getElementById("matchStepLabel"); let current=0,busy=false;
  function show(direction=1){
    steps.forEach((s,i)=>{s.classList.remove("active","enter-forward","enter-back");if(i===current){s.classList.add("active",direction>0?"enter-forward":"enter-back");}});
    bar.style.width=((current+1)/steps.length*100)+"%";
    const phase=current<=2?"Il tuo viaggio":current<=5?"Le tue esigenze":current<=7?"Come vuoi essere seguito":"I tuoi contatti";
    label.textContent=phase+" · "+Math.round((current+1)/steps.length*100)+"%";
    back.hidden=current===0;next.textContent=current===steps.length-1?"Trova i professionisti compatibili →":"Continua →";
  }
  function change(to,direction){if(busy||to<0||to>=steps.length)return;busy=true;const old=steps[current];old.classList.add(direction>0?"exit-left":"exit-right");setTimeout(()=>{old.classList.remove("active","exit-left","exit-right","enter-forward","enter-back");current=to;show(direction);setTimeout(()=>busy=false,380);},260);}
  form.querySelectorAll(".match-options").forEach(group=>group.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",()=>{group.querySelectorAll("button").forEach(b=>b.classList.remove("selected"));btn.classList.add("selected");const hidden=group.parentElement.querySelector('input[type="hidden"]');if(hidden)hidden.value=btn.dataset.value;btn.classList.add("choice-pop");setTimeout(()=>btn.classList.remove("choice-pop"),300);setTimeout(()=>{if(current>0&&current<8)change(current+1,1)},360);})));
  next.addEventListener("click",()=>{if(current===0){const d=form.elements.destination;if(!d.value.trim()&&!form.elements.undecided.checked){d.focus();d.classList.add("match-shake");setTimeout(()=>d.classList.remove("match-shake"),400);return;}} if(current===7){const mode=form.elements.consultation_mode.value;if(!mode)return;} if(current===steps.length-1){if(!form.elements.contact_method.value){form.querySelector(".contact-options")?.classList.add("match-shake");setTimeout(()=>form.querySelector(".contact-options")?.classList.remove("match-shake"),400);return;} if(!form.reportValidity())return;wizard.classList.add("match-completing");setTimeout(()=>{const data=Object.fromEntries(new FormData(form).entries());sessionStorage.setItem("partiBeneTravelMatch",JSON.stringify(data));const q=new URLSearchParams();Object.entries(data).forEach(([k,v])=>q.set(k,v));location.href="professionisti.html?match=1";},550);return;} change(current+1,1);});
  function consultationFee(){const trip=(form.elements.trip_type?.value||"").toLowerCase(),dest=(form.elements.destination?.value||"").toLowerCase();const intercontinental=["usa","stati uniti","america","giappone","japan","maldive","thailandia","australia","canada","messico","brasile","caraibi","africa","asia","indonesia","bali","mauritius","seychelles","zanzibar"];return trip.includes("nozze")||intercontinental.some(x=>dest.includes(x))?50:20;} function refreshFee(){const fee=consultationFee();const price=document.getElementById("consultPrice"),field=document.getElementById("consultationFee");if(price)price.textContent=fee+" €";if(field)field.value=String(fee);} form.addEventListener("input",refreshFee);form.addEventListener("change",refreshFee);back.addEventListener("click",()=>change(current-1,-1));refreshFee();show();
})();