(() => {
  const wizard=document.getElementById("matchWizard"); if(!wizard)return;
  const form=document.getElementById("travelMatchForm"),steps=[...form.querySelectorAll(".match-step")],next=document.getElementById("matchNext"),back=document.getElementById("matchBack"),bar=document.getElementById("matchProgressBar"),label=document.getElementById("matchStepLabel"); let current=0,busy=false;
  function show(direction=1){
    steps.forEach((s,i)=>{s.classList.remove("active","enter-forward","enter-back");if(i===current){s.classList.add("active",direction>0?"enter-forward":"enter-back");}});
    bar.style.width=((current+1)/steps.length*100)+"%";label.textContent="Domanda "+(current+1)+" di "+steps.length;back.hidden=current===0;next.textContent=current===steps.length-1?"Trova il mio Travel Match →":"Continua →";
  }
  function change(to,direction){if(busy||to<0||to>=steps.length)return;busy=true;const old=steps[current];old.classList.add(direction>0?"exit-left":"exit-right");setTimeout(()=>{old.classList.remove("active","exit-left","exit-right","enter-forward","enter-back");current=to;show(direction);setTimeout(()=>busy=false,380);},260);}
  form.querySelectorAll(".match-options").forEach(group=>group.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",()=>{group.querySelectorAll("button").forEach(b=>b.classList.remove("selected"));btn.classList.add("selected");const hidden=group.parentElement.querySelector('input[type="hidden"]');if(hidden)hidden.value=btn.dataset.value;btn.classList.add("choice-pop");setTimeout(()=>btn.classList.remove("choice-pop"),300);setTimeout(()=>{if(current>0&&current<7)change(current+1,1)},360);})));
  next.addEventListener("click",()=>{if(current===0){const d=form.elements.destination;if(!d.value.trim()&&!form.elements.undecided.checked){d.focus();d.classList.add("match-shake");setTimeout(()=>d.classList.remove("match-shake"),400);return;}} if(current===steps.length-1){if(!form.reportValidity())return;wizard.classList.add("match-completing");setTimeout(()=>{const data=Object.fromEntries(new FormData(form).entries());sessionStorage.setItem("partiBeneTravelMatch",JSON.stringify(data));const q=new URLSearchParams();Object.entries(data).forEach(([k,v])=>q.set(k,v));location.href="richiedi-proposte.html?travelmatch=1&"+q.toString();},550);return;} change(current+1,1);});
  back.addEventListener("click",()=>change(current-1,-1));show();
})();